events {
    worker_connections 1024;
}

http {
    # Resolver para DNS dinámico en Docker
    resolver 127.0.0.11:53 valid=10s;
    resolver_timeout 5s;
    
    server {
        server_name localhost;
        listen 3005;
        
        # Proxy para logs OTLP
        location /v1/logs {
            add_header Access-Control-Allow-Origin "http://172.26.190.162:5173" always;
            add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
            add_header Access-Control-Allow-Headers "Authorization, Content-Type, Origin, Accept" always;
            add_header Access-Control-Allow-Credentials "true" always;

            if ($request_method = 'OPTIONS') {
                return 204;
            }

            proxy_pass http://172.26.190.162:4318/v1/logs;
            proxy_buffering off;
            proxy_set_header Host $host;        
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Proxy para traces OTLP
        location /v1/traces {
            add_header Access-Control-Allow-Origin "http://172.26.190.162:5173" always;
            add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
            add_header Access-Control-Allow-Headers "Authorization, Content-Type, Origin, Accept" always;
            add_header Access-Control-Allow-Credentials "true" always;

            if ($request_method = 'OPTIONS') {
                return 204;
            }

            proxy_pass http://172.26.190.162:4318/v1/traces;
            proxy_buffering off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Proxy para metrics OTLP
        location /v1/metrics {
            add_header Access-Control-Allow-Origin "http://172.26.190.162:5173" always;
            add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
            add_header Access-Control-Allow-Headers "Authorization, Content-Type, Origin, Accept" always;
            add_header Access-Control-Allow-Credentials "true" always;

            if ($request_method = 'OPTIONS') {
                return 204;
            }

            proxy_pass http://172.26.190.162:4318/v1/metrics;
            proxy_buffering off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}